### ISSUE TITLE
Mint is crushing

### ISSUE THREAD

**Issue by TheophilosGuinness** [linuxmint/mintreport#25]
===================================================================
 GDB Log                                                           
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 2389]
[New LWP 2393]
[New LWP 2392]
[New LWP 2394]
[New LWP 2564]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007ff5edeb4e97 in ?? ()
[Current thread is 1 (LWP 2389)]

===================================================================
 GDB Backtrace                                                     
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 2389]
[New LWP 2393]
[New LWP 2392]
[New LWP 2394]
[New LWP 2564]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007ff5edeb4e97 in ?? ()
[Current thread is 1 (LWP 2389)]
#0  0x00007ff5edeb4e97 in ?? ()
#1  0x0000000000000000 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 2389]
[New LWP 2393]
[New LWP 2392]
[New LWP 2394]
[New LWP 2564]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007ff5edeb4e97 in ?? ()
[Current thread is 1 (LWP 2389)]

Thread 5 (LWP 2564):
#0  0x00007ff5e97ebc4c in ?? ()
No symbol table info available.
#1  0x0000000003006400 in ?? ()
No symbol table info available.
#2  0x00007ff5e9a33c3a in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 4 (LWP 2394):
#0  0x00007ff5edf8abf9 in ?? ()
No symbol table info available.
#1  0x0000000000000001 in ?? ()
No symbol table info available.
#2  0x00000000021d1f50 in ?? ()
No symbol table info available.
#3  0x00000000021f08a0 in ?? ()
No symbol table info available.
#4  0x0000000000000001 in ?? ()
No symbol table info available.
#5  0x00000000021d1f50 in ?? ()
No symbol table info available.
#6  0x00007ff5e950d539 in ?? ()
No symbol table info available.
#7  0x00007ffc42e29410 in ?? ()
No symbol table info available.
#8  0x00000001021f08a0 in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0x8c36557fc80ba700 in ?? ()
No symbol table info available.
#11 0x0000000000000002 in ?? ()
No symbol table info available.
#12 0x00000000021f08a0 in ?? ()
No symbol table info available.
#13 0x0000000000000001 in ?? ()
No symbol table info available.
#14 0x00007ff5dc93efc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 3 (LWP 2392):
#0  0x00007ff5edf8abf9 in ?? ()
No symbol table info available.
#1  0x0000000000000001 in ?? ()
No symbol table info available.
#2  0x0000000002105b50 in ?? ()
No symbol table info available.
#3  0x0000000002105860 in ?? ()
No symbol table info available.
#4  0x0000000000000001 in ?? ()
No symbol table info available.
#5  0x0000000002105b50 in ?? ()
No symbol table info available.
#6  0x00007ff5e950d539 in ?? ()
No symbol table info available.
#7  0x00007ffc42e28d70 in ?? ()
No symbol table info available.
#8  0x00000001edf0d2ed in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0x8c36557fc80ba700 in ?? ()
No symbol table info available.
#11 0x000000000000002e in ?? ()
No symbol table info available.
#12 0x0000000002105860 in ?? ()
No symbol table info available.
#13 0x0000000000000001 in ?? ()
No symbol table info available.
#14 0x00007ff5e0642fc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (LWP 2393):
#0  0x00007ff5edf8abf9 in ?? ()
No symbol table info available.
#1  0x00000000020852cc in ?? ()
No symbol table info available.
#2  0x0000000002119080 in ?? ()
No symbol table info available.
#3  0x0000000002085180 in ?? ()
No symbol table info available.
#4  0x0000000000000002 in ?? ()
No symbol table info available.
#5  0x0000000002119080 in ?? ()
No symbol table info available.
#6  0x00007ff5e950d539 in ?? ()
No symbol table info available.
#7  0x0000000002119070 in ?? ()
No symbol table info available.
#8  0x0000000102085180 in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0x8c36557fc80ba700 in ?? ()
No symbol table info available.
#11 0x0000000002085b70 in ?? ()
No symbol table info available.
#12 0x00000000020852c0 in ?? ()
No symbol table info available.
#13 0x00000000020852cc in ?? ()
No symbol table info available.
#14 0x00007ff5dfe41fc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (LWP 2389):
#0  0x00007ff5edeb4e97 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
#0  0x00007ff5edeb4e97 in ?? ()
#1  0x0000000000000000 in ?? ()

**Comment by skyline303** [comment]
===================================================================
 GDB Log                                                           
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 3377]
[New LWP 3380]
[New LWP 3381]
[New LWP 3382]
[New LWP 3399]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa0cbb9ee97 in ?? ()
[Current thread is 1 (LWP 3377)]

===================================================================
 GDB Backtrace                                                     
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 3377]
[New LWP 3380]
[New LWP 3381]
[New LWP 3382]
[New LWP 3399]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa0cbb9ee97 in ?? ()
[Current thread is 1 (LWP 3377)]
#0  0x00007fa0cbb9ee97 in ?? ()
#1  0x0000000000000000 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 3377]
[New LWP 3380]
[New LWP 3381]
[New LWP 3382]
[New LWP 3399]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa0cbb9ee97 in ?? ()
[Current thread is 1 (LWP 3377)]

Thread 5 (LWP 3399):
#0  0x00000000004f3f10 in ?? ()
No symbol table info available.
#1  0x0000000000520beb in ?? ()
No symbol table info available.
#2  0x00007fa0cc111048 in ?? ()
No symbol table info available.
#3  0x00000000005a730c in ?? ()
No symbol table info available.
#4  0x00007fa0a4000ce0 in ?? ()
No symbol table info available.
#5  0x0000000000599680 in ?? ()
No symbol table info available.
#6  0x0000000400000004 in ?? ()
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 4 (LWP 3382):
#0  0x00007fa0cbc74bf9 in ?? ()
No symbol table info available.
#1  0x0000000000000001 in ?? ()
No symbol table info available.
#2  0x000000000257d740 in ?? ()
No symbol table info available.
#3  0x0000000002611800 in ?? ()
No symbol table info available.
#4  0x0000000000000001 in ?? ()
No symbol table info available.
#5  0x000000000257d740 in ?? ()
No symbol table info available.
#6  0x00007fa0c7105539 in ?? ()
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 3 (LWP 3381):
#0  0x00007fa0cbc74bf9 in ?? ()
No symbol table info available.
#1  0x000000000245b44c in ?? ()
No symbol table info available.
#2  0x00000000024eefd0 in ?? ()
No symbol table info available.
#3  0x000000000245b300 in ?? ()
No symbol table info available.
#4  0x0000000000000002 in ?? ()
No symbol table info available.
#5  0x00000000024eefd0 in ?? ()
No symbol table info available.
#6  0x00007fa0c7105539 in ?? ()
No symbol table info available.
#7  0x00000000024eefc0 in ?? ()
No symbol table info available.
#8  0x000000010245b300 in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0x9ef7644862586b00 in ?? ()
No symbol table info available.
#11 0x000000000245ba30 in ?? ()
No symbol table info available.
#12 0x000000000245b440 in ?? ()
No symbol table info available.
#13 0x000000000245b44c in ?? ()
No symbol table info available.
#14 0x00007fa0bda40fc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (LWP 3380):
#0  0x00007fa0cbc74bf9 in ?? ()
No symbol table info available.
#1  0x0000000000000001 in ?? ()
No symbol table info available.
#2  0x00000000024db790 in ?? ()
No symbol table info available.
#3  0x00000000024db4a0 in ?? ()
No symbol table info available.
#4  0x0000000000000001 in ?? ()
No symbol table info available.
#5  0x00000000024db790 in ?? ()
No symbol table info available.
#6  0x00007fa0c7105539 in ?? ()
No symbol table info available.
#7  0x00007ffc45ba0b50 in ?? ()
No symbol table info available.
#8  0x00000001cbbf72ed in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0x9ef7644862586b00 in ?? ()
No symbol table info available.
#11 0x000000000000002e in ?? ()
No symbol table info available.
#12 0x00000000024db4a0 in ?? ()
No symbol table info available.
#13 0x0000000000000001 in ?? ()
No symbol table info available.
#14 0x00007fa0be241fc0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (LWP 3377):
#0  0x00007fa0cbb9ee97 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
#0  0x00007fa0cbb9ee97 in ?? ()
#1  0x0000000000000000 in ?? ()
