### ISSUE TITLE
Crash in mintreport when clicking on a crash in sddm

### ISSUE THREAD

**Issue by mauromol** [linuxmint/mintreport#48]
Here is the stack trace. I can't copy it to pastebin because of #47.

```
===================================================================
 GDB Log                                                           
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 15150]
[New LWP 15153]
[New LWP 15155]
[New LWP 15154]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fd36a5ac428 in ?? ()
[Current thread is 1 (LWP 15150)]

===================================================================
 GDB Backtrace                                                     
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 15150]
[New LWP 15153]
[New LWP 15155]
[New LWP 15154]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fd36a5ac428 in ?? ()
[Current thread is 1 (LWP 15150)]
#0  0x00007fd36a5ac428 in ?? ()
#1  0x00007fd36a5ae02a in ?? ()
#2  0x0000000000000020 in ?? ()
#3  0x0000000000000000 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
"/usr/bin/mintreport": not in executable format: File format not recognized
[New LWP 15150]
[New LWP 15153]
[New LWP 15155]
[New LWP 15154]
Core was generated by `mintreport                                                  '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fd36a5ac428 in ?? ()
[Current thread is 1 (LWP 15150)]

Thread 4 (LWP 15154):
#0  0x00007fd36a67274d in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 3 (LWP 15155):
#0  0x00007fd36a67274d in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (LWP 15153):
#0  0x00007fd36a67274d in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (LWP 15150):
#0  0x00007fd36a5ac428 in ?? ()
No symbol table info available.
#1  0x00007fd36a5ae02a in ?? ()
No symbol table info available.
#2  0x0000000000000020 in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.
#0  0x00007fd36a5ac428 in ?? ()
#1  0x00007fd36a5ae02a in ?? ()
#2  0x0000000000000020 in ?? ()
#3  0x0000000000000000 in ?? ()
```

Using Linux Mint 18.3 KDE.

**Comment by JosephMcc** [comment]
Probably not going to be any real action on this. Mintreport was never really meant for 18.3.
